In [1]:
import torch
import argparse
import time
import math
import os, sys
import itertools
import pickle
from tqdm import tqdm
import numpy as np
import os.path as osp

In [2]:
torch.cuda.device_count()

1

In [4]:
a = torch.randn(5, 10)
b = torch.randn(5, 10)
c = torch.einsum('ij,ij->i', a, b)

In [5]:
a

tensor([[-0.0915, -1.0638,  0.7736,  0.9040,  1.5468, -1.7189,  0.1006,  2.2551,
          1.1974,  0.0685],
        [ 1.4588,  0.3196,  0.1219, -0.7941, -1.0080, -2.2741,  0.8354, -1.0704,
          0.1730,  0.8801],
        [-0.0487, -0.8441, -0.6220, -1.0271, -2.1743, -1.2399, -0.6075, -0.4799,
          1.0143, -0.9162],
        [ 1.0284,  0.7337,  0.0296,  0.0255, -2.9406,  0.4970, -0.3213, -0.0674,
          0.6536,  0.7441],
        [-0.1515, -0.1879, -0.3897,  0.9509,  1.2565, -0.5087,  1.1670,  0.6525,
          1.2678, -0.3780]])

In [6]:
b

tensor([[-1.1889,  0.5402, -0.5387, -1.0289,  0.3617,  0.6917,  0.9386, -0.2878,
          1.7546,  0.7516],
        [-1.1264,  0.4338, -0.6542, -1.8350, -0.0124, -2.5025,  0.0984, -0.2196,
          1.3807,  1.1668],
        [-0.3692, -1.4367,  1.4941,  0.0331, -0.2852, -1.0265,  0.8621, -0.8295,
         -0.0525, -0.0734],
        [-1.4226, -0.9828,  1.4360,  0.1696, -0.1918, -0.6819,  0.4225,  0.7971,
         -0.0228, -0.5700],
        [ 0.4731, -0.9556, -1.6145,  0.2961,  1.4389,  1.1300,  1.0665, -1.3910,
         -1.1682,  1.1470]])

In [7]:
c

tensor([-0.8442,  7.1592,  2.0485, -2.5406,  0.6740])

In [9]:
a[1]@b[1].T

tensor(7.1592)